Repository joshzcold/Friendly-Feud, pull requests merged in 2025-01, with the labels that each got.

#138 chore(deps): bump the npm group with 3 updates
  package-lock.json
  package.json
Labels: dependencies

#136 Docker healthcheck
  .gitignore
  Dockerfile
  backend/Dockerfile
  backend/api/health.go
  backend/main.go
  chart/templates/deployment.yaml
  docker/docker-compose-dev-wsl.yaml
  docker/docker-compose-dev.yaml
  docker/docker-compose.yaml
  e2e/playwright-dev.config.js
  e2e/playwright-prod.config.js
  e2e/playwright.config.js
  e2e/tests/admin.spec.js
  e2e/tests/global.setup.ts
Labels: enhancement

#140 Upgrade Next from 11 to 12
  Dockerfile
  Dockerfile.allinone
  components/Admin/settings.js
  components/Title/TitlePage.jsx
  components/admin.js
  components/buzzer.js
  components/team-name.js
  docker/allinone/nginx.conf
  docker/docker-compose-dev-wsl.yaml
  docker/docker-compose-dev.yaml
  docker/nginx/nginx.conf
  docker/nginx/nginx.wsl.conf
  next.config.js
  package-lock.json
  package.json
  pages/_app.js
  pages/game.js
  pages/index.js
  public/favicon/apple-icon.png
  public/favicon/favicon.ico
  public/favicon/icon.png
  public/favicon/icon.svg
  public/favicon/manifest.json
  public/favicon/web-app-manifest-192x192.png
  public/favicon/web-app-manifest-512x512.png
  public/locales/et/translation.json
Labels: enhancement

#142 Upgrade Next from 12 to 13
  components/Login/Footer.jsx
  components/Title/TitlePage.jsx
  components/admin.js
  components/buzzer.js
  components/team-name.js
  e2e/tests/admin.spec.js
  package-lock.json
  package.json
  pages/_app.js
Labels: enhancement

#145 fix(goroutine): add missing loop into gameTimeout
  backend/api/game.go
  backend/api/room.go
  backend/api/session.go
  backend/main.go
Labels: bug

#146 feat(ui): add version indicator to home page
  .env
  components/Login/Footer.jsx
  components/Title/Version.jsx
  package.json
  public/locales/en/translation.json
  public/locales/et/translation.json
Labels: enhancement

#148 Upgrade to Next 14.2 and Node 20
  Dockerfile
  Dockerfile.allinone
  next.config.js
  package-lock.json
  package.json
Labels: dependencies

#147 Dev changes
  .dockerignore
  .eslintignore
  .eslintrc.json
  .gitignore
  .husky/pre-commit
  .prettierrc
  Dockerfile
  Dockerfile.allinone
  Dockerfile.allinone.dockerignore
  components/admin.js
  docker/allinone/start.sh
  docker/docker-compose-dev-wsl.yaml
  docker/docker-compose-dev.yaml
  e2e/tests/admin.spec.js
  e2e/tests/new.spec.js
  i18n/i18next-scanner.config.js
  jsconfig.json
  next-env.d.ts
  next.config.js
  package-lock.json
  package.json
  src/components/Admin/CSVLoader.jsx
  src/components/Admin/Players.jsx
  src/components/Admin/Settings.jsx
  src/components/Admin/ThemeSwitcher.jsx
  src/components/AdminPage.jsx
  src/components/BuzzerPage.jsx
  src/components/BuzzerPopup.jsx
  src/components/BuzzerTable.jsx
  src/components/FinalPage.jsx
  src/components/LanguageSwitcher.jsx
  src/components/Login/Footer.jsx
  src/components/LoginPage.jsx
  src/components/QuestionBoard.jsx
  src/components/Round.jsx
  src/components/TeamName.jsx
  src/components/ThemeProvider.jsx
  src/components/Title/RoomCode.jsx
  src/components/Title/Team.jsx
  src/components/Title/TitlePage.jsx
  src/components/Title/Version.jsx
  src/components/TitleLogo.jsx
  src/components/ui/tooltip.jsx
  src/global.css
  src/lib/utils/files.js
  src/lib/utils/index.ts
  src/pages/_app.jsx
  src/pages/game.jsx
  src/pages/index.jsx
  src/pages/new.jsx
  tailwind.config.js
  tsconfig.json
Labels: enhancement, dependencies

#153 fix(health): support SQLite stores in checkDatabase
  backend/api/health.go
  backend/api/store-memory.go
  backend/api/store-sqlite.go
  backend/api/store.go
Labels: bug

#156 fix(buzzer): add buzzer sound settings to struct
  backend/api/game.go
  src/components/Admin/Settings.jsx
  src/components/BuzzerPage.jsx
  src/components/BuzzerPopup.jsx
Labels: bug

#155 feat(security): add host/player validation for quit operations
  backend/api/errors.go
  backend/api/session.go
  public/locales/en/translation.json
  public/locales/et/translation.json
Labels: enhancement

#157 fix(buzzer) include check for when player refreshes page and they already buzzed
  src/components/BuzzerPage.jsx
Labels: bug

#161 fix(ui): make file upload of game more obvious
  public/locales/en/translation.json
  public/locales/et/translation.json
  src/components/Admin/GameLoader.jsx
  src/components/AdminPage.jsx
  src/lib/utils/files.js
  src/lib/utils/index.ts
Labels: bug, enhancement

#162 fix(admin): better validation for uploaded games
  public/locales/en/translation.json
  public/locales/et/translation.json
  src/components/Admin/AdminSettings/BuzzerSoundSettings.jsx
  src/components/Admin/AdminSettings/FinalRoundTitleChanger.jsx
  src/components/Admin/AdminSettings/HideGameQuestions.jsx
  src/components/Admin/AdminSettings/index.jsx
  src/components/AdminPage.jsx
  src/lib/utils/debounce.js
  src/lib/utils/files.js
  src/lib/utils/index.ts
  src/pages/new.jsx
Labels: enhancement

#160 docs: Create documentation on development
  doc/development.md
  readme.md
Labels: documentation

#186 Refactor e2e part 2
  e2e/tests/admin/admin.spec.ts
  e2e/tests/admin/settings.spec.ts
  e2e/tests/buzzer.spec.js
  e2e/tests/game.spec.js
  e2e/tests/lib/Setup.js
  e2e/tests/lib/Setup.ts
  e2e/tests/models/GamePage.js
  e2e/tests/new.spec.js
Labels: enhancement
